name: Build and Push CPU Container

on:
  release:
    types: [created]
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      force_push:
        type: boolean
        description: "Do you want to push image after build?"
        default: false

env:
  VERSION: "0.0.0" # Default version, will be overwritten
  RKNN_VERSION: "1.6.0"

jobs:
  docker-cpu:
    runs-on:
      labels: ubuntu-latest
    timeout-minutes: 120
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: ðŸ›Žï¸ Checkout
        uses: actions/checkout@v4
      - name: Read version from file
        run: echo "VERSION=$(DISABLE_VERSION_CHECK=true python version.py)" >> $GITHUB_ENV
      - name: Set up Depot CLI
        uses: depot/setup-action@v1
      - name: Build and Push
        uses: depot/build-push-action@v1
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/coral-inference-server-cpu:latest,roboflow/coral-inference-server-cpu:${{env.VERSION}}
          platforms: linux/amd64,linux/arm64
          file: ./docker/dockerfiles/Dockerfile.cpu
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/coral-inference-server-cpu:latest
          cache-to: type=inline

  docker-gpu:
    runs-on:
      labels: ubuntu-latest
    timeout-minutes: 120
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: ðŸ›Žï¸ Checkout
        uses: actions/checkout@v4
      - name: Read version from file
        run: echo "VERSION=$(DISABLE_VERSION_CHECK=true python version.py)" >> $GITHUB_ENV
      - name: Set up Depot CLI
        uses: depot/setup-action@v1
      - name: Build and Push
        uses: depot/build-push-action@v1
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/coral-inference-server-gpu:latest,roboflow/coral-inference-server-gpu:${{env.VERSION}}
          platforms: linux/amd64,linux/arm64
          file: ./docker/dockerfiles/Dockerfile.gpu
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/coral-inference-server-gpu:latest
          cache-to: type=inline

  docker-rknn:
    runs-on:
      labels: ubuntu-latest
    timeout-minutes: 120
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: ðŸ›Žï¸ Checkout
        uses: actions/checkout@v4
      - name: Read version from file
        run: echo "VERSION=$(DISABLE_VERSION_CHECK=true python version.py)" >> $GITHUB_ENV
      - name: Set up Depot CLI
        uses: depot/setup-action@v1
      - name: Build and Push
        uses: depot/build-push-action@v1
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/coral-inference-server-rknn:latest-rknn${{env.RKNN_VERSION}},roboflow/coral-inference-server-rknn:${{env.VERSION}}-rknn${{env.RKNN_VERSION}}
          platforms: linux/amd64,linux/arm64
          file: ./docker/dockerfiles/Dockerfile.rknn
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/coral-inference-server-rknn:latest-rknn${{env.RKNN_VERSION}}
          cache-to: type=inline
